### ISSUE TITLE
is there an opportunity to make a .mcvd files decoding?

### ISSUE THREAD

**Issue by Fadeyauso** [onejeuu/sc-file#1]
i think it's animations

**Comment by onejeuu** [comment]
Most likely yes, it's an animations format.

Unfortunately like some other text files (.mcxd, .t, etc), it's encrypted with block cipher or something. 

I haven't been able to figure out exactly what it is.

**Comment by Fadeyauso** [comment]
sadly then

**Comment by onejeuu** [comment]
Although no, I got them confused with another format (.mcal)

Format .mcvd is a collider or something like that. You could try renaming suffix to .mcsa and maybe that would work. But I don't guarantee it.

**Comment by Fadeyauso** [comment]
so animations is an .mcvd or what?

**Comment by Fadeyauso** [comment]
i think actually .mcal it's the animations but in what format the were been before the .mcal extension

**Comment by Fadeyauso** [comment]
actually there is another extension named .anm and idk what is that bruh

**Comment by onejeuu** [comment]
`.mcxd` is a material properties.

`.mcal` not sure. They are only for weapons, most likely related to first person rendering. Probably some animations. So original format is unknown.

`.anm` is not encrypted, but where it is used is not sure.

**Comment by Fadeyauso** [comment]
btw is there an opportunity to convert the obj to .mcsa or .png to .mic

**Comment by Fadeyauso** [comment]
and what's the .ol format like i spotted it in the map files i'm just curious can i rly recreate the map by that

**Comment by onejeuu** [comment]
It's possible, but without me. File replacement in detect, so pretty useless.

**Comment by Fadeyauso** [comment]
well editing the txt's and other don't really seem detected
