### ISSUE TITLE
After last update .mcsa structure updated

### ISSUE THREAD

**Issue by m1dokin** [onejeuu/sc-file#2]
Error code: ...\models\armor\ao1\ao1.mcsa - 'utf-8' codec can't decode byte 0xbd in
position 0: invalid start byte

**Comment by onejeuu** [comment]
Are you sure you are using [latest version](https://github.com/onejeuu/sc-file/releases/latest)? I don't see any problems with this file. Older versions may not support all models.

![image](https://github.com/onejeuu/sc-file/assets/77905539/6d35389d-badb-4c77-ab3c-1f70886d40de)

**Comment by m1dokin** [comment]
Sorry, my bad, i suppose i have corrupted game files. Anyway thanks!
