### ISSUE TITLE
Bones unlinked with body

### ISSUE THREAD

**Issue by eternalavarice** [onejeuu/sc-file#5]
Why bones unlinked with model?
![image](https://github.com/onejeuu/sc-file/assets/140763566/fd2ed3f1-b095-450e-b713-cf8e51b8bfd4)

**Comment by onejeuu** [comment]
Skeleton currently are not fully implemented.
Third-party converters are unlikely to be able create right rig from ms3d.

If someone is good at this, they can always create a PR.
